# -*- coding: utf-8 -*-
"""HealthAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJ_fQACLZtLTqnFqcbk2zr0FWToUl1uy
"""

!pip install transformers torch gradio -q

